Repository ASelfridge/Stew-Dio, pull requests merged in 2019-02, with the labels that each got.

#41 Alpha environment
  3DProduction/stagingEnvironment/scenes/modeling/character_model.ma
  3DProduction/stagingEnvironment/scenes/referenceObjects/character_reference.ma
  package-lock.json
  package.json
  public/assets/models/bowl.mtl
  public/assets/models/bowl.obj
  public/assets/models/bowl_model.ma
  public/assets/models/carrot.obj
  public/assets/models/character.mtl
  public/assets/models/character.obj
  public/assets/models/customerService.mtl
  public/assets/models/customerService.obj
  public/assets/models/cuttingBoard.obj
  public/assets/models/ingredientStation.obj
  public/assets/models/knife.obj
  public/assets/models/ladle.obj
  public/assets/models/pot.obj
  public/assets/models/recipeBook.obj
  public/assets/models/stove.obj
  public/assets/models/table.obj
  public/assets/textures/sunsetGradient.png
  public/index.html
Labels: A-Frame Development

#43 Mobile controls
  public/index.html
  public/js/deviceControls.js
Labels: Logic Implementation

#42 Oculus controls
  public/index.html
  public/js/deviceControls.js
Labels: Logic Implementation

#50 added physics.
  package-lock.json
  public/assets/models/fryingPan.mtl
  public/assets/models/fryingPan.obj
  public/assets/models/ingredient.mtl
  public/assets/models/ingredient.obj
  public/assets/models/pan_model.ma
  public/index.html
  public/js/object-pickup.js
  public/js/object-place.js
Labels: A-Frame Development, Logic Implementation
